title: harshaheg.de
description: >- # this means to ignore newlines until "baseurl:"
  Ver. 1.0.3
domain: harshakhegde.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://harshakhegde.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""      # place folder name if the site is served in a subfolder
header_pages:
  - wisdom.markdown
  - about.markdown
remote_theme: jekyll/minima
minima:
  skin: solarized
  social_links:
    - { platform: github,  user_url: "https://github.com/harshakhegde" }
    - { platform: x, user_url: "https://x.com/harshahegdek" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/harshakhegde/" }
plugins:
  - jekyll-feed
  - jekyll-remote-theme 